# Generated by Django 5.2.14 on 2026-06-04 22:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('nome_completo', models.CharField(max_length=200)),
                ('nis', models.CharField(max_length=11, unique=True)),
                ('data_nascimento', models.DateField()),
                ('estado_civil', models.CharField(choices=[('solteiro', 'Solteiro(a)'), ('casado', 'Casado(a)'), ('divorciado', 'Divorciado(a)'), ('viuvo', 'Viúvo(a)'), ('uniao_estavel', 'União Estável')], max_length=20)),
                ('grau_instrucao', models.CharField(choices=[('fundamental', 'Ensino Fundamental'), ('medio', 'Ensino Médio'), ('superior', 'Ensino Superior'), ('pos', 'Pós-graduação')], max_length=20)),
                ('sexo', models.CharField(choices=[('masculino', 'Masculino'), ('feminino', 'Feminino'), ('outro', 'Outro')], max_length=10)),
                ('telefone1', models.CharField(max_length=15)),
                ('profissao', models.CharField(max_length=100)),
                ('nome_mae', models.CharField(max_length=200)),
                ('nome_pai', models.CharField(blank=True, max_length=200, null=True)),
                ('possui_deficiencia', models.BooleanField(default=False)),
                ('possui_doenca_rara', models.BooleanField(default=False)),
                ('mulher_responsavel_familia', models.BooleanField(default=False)),
                ('renda_pessoal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('posicao_familiar', models.CharField(choices=[('chefe', 'Chefe de família'), ('conjuge', 'Cônjuge'), ('filho', 'Filho(a)'), ('outro', 'Outro')], max_length=20)),
                ('renda_comprovada', models.BooleanField(default=False)),
                ('numero_pessoas_familia', models.IntegerField()),
                ('renda_familiar', models.DecimalField(decimal_places=2, max_digits=10)),
                ('recebe_bolsa_familia', models.BooleanField(default=False)),
                ('deficiencia_na_familia', models.BooleanField(default=False)),
                ('doenca_rara_na_familia', models.BooleanField(default=False)),
                ('recebe_bpc', models.BooleanField(default=False)),
                ('pessoa_negra_na_familia', models.BooleanField(default=False)),
                ('mulheres_violencia_domestica', models.BooleanField(default=False)),
                ('povos_tradicionais_quilombolas', models.BooleanField(default=False)),
                ('idosos_na_familia', models.BooleanField(default=False)),
                ('contrato_rescindido', models.BooleanField(default=False)),
                ('microcefalia_na_familia', models.BooleanField(default=False)),
                ('filhos_0_6', models.IntegerField(default=0)),
                ('filhos_7_11', models.IntegerField(default=0)),
                ('filhos_12_18', models.IntegerField(default=0)),
                ('residente_area_risco', models.BooleanField(default=False)),
                ('situacao_rua', models.BooleanField(default=False)),
                ('data_cadastro', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_alteracao', models.DateTimeField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
    ]
