# Generated by Django 5.2.14 on 2026-06-05 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_municipio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beneficiario',
            name='grau_instrucao',
        ),
        migrations.RemoveField(
            model_name='beneficiario',
            name='nome_mae',
        ),
        migrations.RemoveField(
            model_name='beneficiario',
            name='nome_pai',
        ),
        migrations.RemoveField(
            model_name='beneficiario',
            name='profissao',
        ),
        migrations.RemoveField(
            model_name='beneficiario',
            name='renda_comprovada',
        ),
        migrations.RemoveField(
            model_name='beneficiario',
            name='telefone1',
        ),
        migrations.AlterField(
            model_name='beneficiario',
            name='estado_civil',
            field=models.CharField(choices=[('casado', 'Casado(a)'), ('separado', 'Separado(a)'), ('divorciado', 'Divorciado(a)'), ('uniao_estavel', 'Em união estável'), ('companheiro(a)', 'Mora com companheiro(a)'), ('solteiro', 'Solteiro(a)'), ('viuvo', 'Viúvo(a)')], max_length=20),
        ),
        migrations.AlterField(
            model_name='beneficiario',
            name='sexo',
            field=models.CharField(choices=[('masculino', 'Masculino'), ('feminino', 'Feminino')], max_length=10),
        ),
    ]
