# Generated by Django 5.2.14 on 2026-06-05 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_municipio', '0002_remove_beneficiario_grau_instrucao_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='beneficiario',
            old_name='contrato_rescindido',
            new_name='beneficiario_contrato_rescindido',
        ),
        migrations.AlterField(
            model_name='beneficiario',
            name='numero_pessoas_familia',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='beneficiario',
            name='renda_pessoal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
