# Generated by Django 5.2.14 on 2026-06-06 02:04

import django.core.validators
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_municipio', '0003_rename_contrato_rescindido_beneficiario_beneficiario_contrato_rescindido_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beneficiario',
            name='data_alteracao',
        ),
        migrations.AddField(
            model_name='beneficiario',
            name='data_ultima_alteracao',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='beneficiario',
            name='situacao_cadastral',
            field=models.CharField(choices=[('em_analise', 'Em análise'), ('contemplado', 'Contemplado'), ('indeferido', 'Indeferido')], default='em_analise', max_length=20),
        ),
        migrations.AlterField(
            model_name='beneficiario',
            name='cpf',
            field=models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message='CPF deve conter 11 dígitos.', regex='^\\d{11}$')]),
        ),
        migrations.AlterField(
            model_name='beneficiario',
            name='data_cadastro',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='beneficiario',
            name='estado_civil',
            field=models.CharField(choices=[('casado', 'Casado(a)'), ('separado', 'Separado(a)'), ('divorciado', 'Divorciado(a)'), ('uniao_estavel', 'Em união estável'), ('companheiro', 'Mora com companheiro(a)'), ('solteiro', 'Solteiro(a)'), ('viuvo', 'Viúvo(a)')], max_length=20),
        ),
        migrations.AlterField(
            model_name='beneficiario',
            name='filhos_0_6',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='beneficiario',
            name='filhos_12_18',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='beneficiario',
            name='filhos_7_11',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='beneficiario',
            name='nis',
            field=models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message='NIS deve conter 11 dígitos.', regex='^\\d{11}$')]),
        ),
        migrations.AlterField(
            model_name='beneficiario',
            name='numero_pessoas_familia',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.CreateModel(
            name='HistoricalBeneficiario',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('cpf', models.CharField(db_index=True, max_length=11, validators=[django.core.validators.RegexValidator(message='CPF deve conter 11 dígitos.', regex='^\\d{11}$')])),
                ('nome_completo', models.CharField(max_length=200)),
                ('nis', models.CharField(db_index=True, max_length=11, validators=[django.core.validators.RegexValidator(message='NIS deve conter 11 dígitos.', regex='^\\d{11}$')])),
                ('data_nascimento', models.DateField()),
                ('estado_civil', models.CharField(choices=[('casado', 'Casado(a)'), ('separado', 'Separado(a)'), ('divorciado', 'Divorciado(a)'), ('uniao_estavel', 'Em união estável'), ('companheiro', 'Mora com companheiro(a)'), ('solteiro', 'Solteiro(a)'), ('viuvo', 'Viúvo(a)')], max_length=20)),
                ('sexo', models.CharField(choices=[('masculino', 'Masculino'), ('feminino', 'Feminino')], max_length=10)),
                ('possui_deficiencia', models.BooleanField(default=False)),
                ('possui_doenca_rara', models.BooleanField(default=False)),
                ('mulher_responsavel_familia', models.BooleanField(default=False)),
                ('renda_pessoal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('posicao_familiar', models.CharField(choices=[('chefe', 'Chefe de família'), ('conjuge', 'Cônjuge'), ('filho', 'Filho(a)'), ('outro', 'Outro')], max_length=20)),
                ('numero_pessoas_familia', models.PositiveIntegerField(default=1)),
                ('renda_familiar', models.DecimalField(decimal_places=2, max_digits=10)),
                ('recebe_bolsa_familia', models.BooleanField(default=False)),
                ('deficiencia_na_familia', models.BooleanField(default=False)),
                ('doenca_rara_na_familia', models.BooleanField(default=False)),
                ('recebe_bpc', models.BooleanField(default=False)),
                ('pessoa_negra_na_familia', models.BooleanField(default=False)),
                ('mulheres_violencia_domestica', models.BooleanField(default=False)),
                ('povos_tradicionais_quilombolas', models.BooleanField(default=False)),
                ('idosos_na_familia', models.BooleanField(default=False)),
                ('beneficiario_contrato_rescindido', models.BooleanField(default=False)),
                ('microcefalia_na_familia', models.BooleanField(default=False)),
                ('filhos_0_6', models.PositiveIntegerField(default=0)),
                ('filhos_7_11', models.PositiveIntegerField(default=0)),
                ('filhos_12_18', models.PositiveIntegerField(default=0)),
                ('residente_area_risco', models.BooleanField(default=False)),
                ('situacao_rua', models.BooleanField(default=False)),
                ('situacao_cadastral', models.CharField(choices=[('em_analise', 'Em análise'), ('contemplado', 'Contemplado'), ('indeferido', 'Indeferido')], default='em_analise', max_length=20)),
                ('data_cadastro', models.DateTimeField(blank=True, editable=False)),
                ('data_ultima_alteracao', models.DateTimeField(blank=True, editable=False)),
                ('ativo', models.BooleanField(default=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical beneficiario',
                'verbose_name_plural': 'historical beneficiarios',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
