# Generated by Django 5.2.14 on 2026-06-06 19:31

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_municipio', '0004_remove_beneficiario_data_alteracao_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CriterioPontuacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('descricao', models.CharField(max_length=255)),
                ('campo_beneficiario', models.CharField(choices=[('possui_deficiencia', 'Possui deficiência'), ('possui_doenca_rara', 'Possui doença rara'), ('mulher_responsavel_familia', 'Mulher responsável pela família'), ('recebe_bolsa_familia', 'Recebe Bolsa Família'), ('deficiencia_na_familia', 'Deficiência na família'), ('doenca_rara_na_familia', 'Doença rara na família'), ('recebe_bpc', 'Recebe BPC'), ('pessoa_negra_na_familia', 'Pessoa negra na família'), ('mulheres_violencia_domestica', 'Mulheres vítimas de violência doméstica'), ('povos_tradicionais_quilombolas', 'Povos tradicionais e quilombolas'), ('idosos_na_familia', 'Idosos na família'), ('beneficiario_contrato_rescindido', 'Contrato rescindido'), ('microcefalia_na_familia', 'Microcefalia na família'), ('filhos_0_6', 'Filhos de 0 a 6 anos'), ('filhos_7_11', 'Filhos de 7 a 11 anos'), ('filhos_12_18', 'Filhos de 12 a 18 anos'), ('residente_area_risco', 'Residente em área de risco'), ('situacao_rua', 'Situação de rua')], max_length=100)),
                ('pontos', models.PositiveIntegerField(help_text='Quantidade de pontos atribuída ao critério')),
                ('tipo_calculo', models.CharField(choices=[('fixo', 'Fixo'), ('multiplicador', 'Multiplicador')], default='fixo', max_length=20)),
                ('fundamentacao_legal', models.CharField(blank=True, max_length=255)),
                ('ativo', models.BooleanField(default=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Critério de Pontuação',
                'verbose_name_plural': 'Critérios de Pontuação',
                'ordering': ['descricao'],
            },
        ),
        migrations.AlterModelOptions(
            name='beneficiario',
            options={'ordering': ['nome_completo'], 'verbose_name': 'Beneficiário', 'verbose_name_plural': 'Beneficiários'},
        ),
        migrations.AlterModelOptions(
            name='historicalbeneficiario',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Beneficiário', 'verbose_name_plural': 'historical Beneficiários'},
        ),
        migrations.CreateModel(
            name='HistoricalCriterioPontuacao',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('codigo', models.CharField(db_index=True, max_length=50)),
                ('descricao', models.CharField(max_length=255)),
                ('campo_beneficiario', models.CharField(choices=[('possui_deficiencia', 'Possui deficiência'), ('possui_doenca_rara', 'Possui doença rara'), ('mulher_responsavel_familia', 'Mulher responsável pela família'), ('recebe_bolsa_familia', 'Recebe Bolsa Família'), ('deficiencia_na_familia', 'Deficiência na família'), ('doenca_rara_na_familia', 'Doença rara na família'), ('recebe_bpc', 'Recebe BPC'), ('pessoa_negra_na_familia', 'Pessoa negra na família'), ('mulheres_violencia_domestica', 'Mulheres vítimas de violência doméstica'), ('povos_tradicionais_quilombolas', 'Povos tradicionais e quilombolas'), ('idosos_na_familia', 'Idosos na família'), ('beneficiario_contrato_rescindido', 'Contrato rescindido'), ('microcefalia_na_familia', 'Microcefalia na família'), ('filhos_0_6', 'Filhos de 0 a 6 anos'), ('filhos_7_11', 'Filhos de 7 a 11 anos'), ('filhos_12_18', 'Filhos de 12 a 18 anos'), ('residente_area_risco', 'Residente em área de risco'), ('situacao_rua', 'Situação de rua')], max_length=100)),
                ('pontos', models.PositiveIntegerField(help_text='Quantidade de pontos atribuída ao critério')),
                ('tipo_calculo', models.CharField(choices=[('fixo', 'Fixo'), ('multiplicador', 'Multiplicador')], default='fixo', max_length=20)),
                ('fundamentacao_legal', models.CharField(blank=True, max_length=255)),
                ('ativo', models.BooleanField(default=True)),
                ('data_cadastro', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Critério de Pontuação',
                'verbose_name_plural': 'historical Critérios de Pontuação',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
