# Generated by Django 5.2.14 on 2026-06-06 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_municipio', '0005_criteriopontuacao_alter_beneficiario_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='criteriopontuacao',
            name='codigo',
        ),
        migrations.RemoveField(
            model_name='historicalcriteriopontuacao',
            name='codigo',
        ),
        migrations.AlterField(
            model_name='criteriopontuacao',
            name='campo_beneficiario',
            field=models.CharField(choices=[('possui_deficiencia', 'Possui deficiência'), ('possui_doenca_rara', 'Possui doença rara'), ('mulher_responsavel_familia', 'Mulher responsável pela família'), ('recebe_bolsa_familia', 'Recebe Bolsa Família'), ('deficiencia_na_familia', 'Deficiência na família'), ('doenca_rara_na_familia', 'Doença rara na família'), ('recebe_bpc', 'Recebe BPC'), ('pessoa_negra_na_familia', 'Pessoa negra na família'), ('mulheres_violencia_domestica', 'Mulheres vítimas de violência doméstica'), ('povos_tradicionais_quilombolas', 'Povos tradicionais e quilombolas'), ('idosos_na_familia', 'Idosos na família'), ('beneficiario_contrato_rescindido', 'Contrato rescindido'), ('microcefalia_na_familia', 'Microcefalia na família'), ('filhos_0_6', 'Filhos de 0 a 6 anos'), ('filhos_7_11', 'Filhos de 7 a 11 anos'), ('filhos_12_18', 'Filhos de 12 a 18 anos'), ('residente_area_risco', 'Residente em área de risco'), ('situacao_rua', 'Situação de rua')], max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='historicalcriteriopontuacao',
            name='campo_beneficiario',
            field=models.CharField(choices=[('possui_deficiencia', 'Possui deficiência'), ('possui_doenca_rara', 'Possui doença rara'), ('mulher_responsavel_familia', 'Mulher responsável pela família'), ('recebe_bolsa_familia', 'Recebe Bolsa Família'), ('deficiencia_na_familia', 'Deficiência na família'), ('doenca_rara_na_familia', 'Doença rara na família'), ('recebe_bpc', 'Recebe BPC'), ('pessoa_negra_na_familia', 'Pessoa negra na família'), ('mulheres_violencia_domestica', 'Mulheres vítimas de violência doméstica'), ('povos_tradicionais_quilombolas', 'Povos tradicionais e quilombolas'), ('idosos_na_familia', 'Idosos na família'), ('beneficiario_contrato_rescindido', 'Contrato rescindido'), ('microcefalia_na_familia', 'Microcefalia na família'), ('filhos_0_6', 'Filhos de 0 a 6 anos'), ('filhos_7_11', 'Filhos de 7 a 11 anos'), ('filhos_12_18', 'Filhos de 12 a 18 anos'), ('residente_area_risco', 'Residente em área de risco'), ('situacao_rua', 'Situação de rua')], db_index=True, max_length=100),
        ),
    ]
