# Generated by Django 5.2.14 on 2026-06-06 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_municipio', '0006_remove_criteriopontuacao_codigo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiario',
            name='pontuacao',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='historicalbeneficiario',
            name='pontuacao',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
